# Generated by Django 5.1.3 on 2025-03-22 06:42

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("other", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Job",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, db_index=True, null=True),
                ),
                ("updated_at", models.DateTimeField(auto_now=True, null=True)),
                ("meta", models.JSONField(blank=True, null=True)),
                (
                    "uuid",
                    models.UUIDField(db_index=True, default=uuid.uuid4, unique=True),
                ),
                ("is_deleted", models.BooleanField(db_index=True, default=False)),
                ("title", models.CharField(blank=True, max_length=255, null=True)),
                ("department", models.CharField(blank=True, max_length=255, null=True)),
                ("location", models.CharField(blank=True, max_length=255, null=True)),
                (
                    "type",
                    models.CharField(
                        choices=[
                            ("FULL_TIME", "full_time"),
                            ("PART_TIME", "part_time"),
                            ("CONTRACT", "contract"),
                            ("INTERN", "intern"),
                            ("TEMPORARY", "temporary"),
                            ("VOLUNTEER", "volunteer"),
                            ("FREELANCE", "freelance"),
                        ],
                        max_length=255,
                    ),
                ),
                ("posted", models.DateTimeField(auto_now_add=True)),
                ("description", models.TextField(blank=True, null=True)),
            ],
            options={
                "get_latest_by": "updated_at",
                "abstract": False,
            },
        ),
    ]
