# Generated by Django 5.1.3 on 2025-01-24 11:08

import uuid

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="EmailTemplate",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, db_index=True, null=True),
                ),
                ("updated_at", models.DateTimeField(auto_now=True, null=True)),
                ("meta", models.JSONField(blank=True, null=True)),
                (
                    "uuid",
                    models.UUIDField(db_index=True, default=uuid.uuid4, unique=True),
                ),
                ("is_deleted", models.BooleanField(db_index=True, default=False)),
                (
                    "template_type",
                    models.CharField(
                        choices=[
                            ("OTP", "otp"),
                            ("RESET_PASSWORD", "reset_password"),
                            ("VERIFY_EMAIL", "verify_email"),
                        ],
                        max_length=255,
                    ),
                ),
                ("is_hidden", models.BooleanField(default=False)),
                ("template", models.TextField(blank=True, null=True)),
                ("is_active", models.BooleanField(default=True)),
            ],
            options={
                "get_latest_by": "updated_at",
                "abstract": False,
            },
        ),
    ]
