# Generated by Django 5.1.3 on 2025-01-16 11:08

import uuid

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("user", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Investment",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, db_index=True, null=True),
                ),
                ("updated_at", models.DateTimeField(auto_now=True, null=True)),
                ("meta", models.JSONField(blank=True, null=True)),
                (
                    "uuid",
                    models.UUIDField(db_index=True, default=uuid.uuid4, unique=True),
                ),
                ("is_deleted", models.BooleanField(db_index=True, default=False)),
                ("amount", models.FloatField(null=True)),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        to="user.user",
                    ),
                ),
            ],
            options={
                "get_latest_by": "updated_at",
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="InvestmentReturn",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, db_index=True, null=True),
                ),
                ("updated_at", models.DateTimeField(auto_now=True, null=True)),
                ("meta", models.JSONField(blank=True, null=True)),
                (
                    "uuid",
                    models.UUIDField(db_index=True, default=uuid.uuid4, unique=True),
                ),
                ("is_deleted", models.BooleanField(db_index=True, default=False)),
                ("return_in_amount", models.FloatField(null=True)),
                ("return_in_percent", models.FloatField(null=True)),
                ("amount_settled", models.FloatField(null=True)),
                ("credited_to_account", models.BooleanField(default=False)),
                ("amount_credit_date", models.DateTimeField()),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="returns",
                        to="user.user",
                    ),
                ),
            ],
            options={
                "get_latest_by": "updated_at",
                "abstract": False,
            },
        ),
    ]
