# Generated by Django 5.1.3 on 2025-03-14 10:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("investment", "0003_userpropertyreturntypeinvestment"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Transaction",
        ),
    ]
