# Generated by Django 5.1.3 on 2025-03-16 07:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("investment", "0004_delete_transaction"),
    ]

    operations = [
        migrations.AlterField(
            model_name="investmentreturn",
            name="return_type",
            field=models.CharField(
                choices=[
                    ("RENT", "rent"),
                    ("APPRECIATION", "appriciation"),
                    ("OTHER", "other"),
                ],
                default="RENTAL",
                max_length=255,
                null=True,
            ),
        ),
    ]
