# Generated by Django 5.1.3 on 2025-03-07 15:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("user", "0003_wishlist"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="is_2fa_enabled",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="user",
            name="secret_key",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
