# Generated by Django 5.1.3 on 2025-01-16 11:08

import uuid

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Property",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, db_index=True, null=True),
                ),
                ("updated_at", models.DateTimeField(auto_now=True, null=True)),
                ("meta", models.JSONField(blank=True, null=True)),
                (
                    "uuid",
                    models.UUIDField(db_index=True, default=uuid.uuid4, unique=True),
                ),
                ("is_deleted", models.BooleanField(db_index=True, default=False)),
                ("name", models.CharField(blank=True, max_length=255, null=True)),
                ("address", models.TextField(blank=True, null=True)),
                ("description", models.TextField(blank=True, null=True)),
                (
                    "type",
                    models.CharField(
                        choices=[
                            ("RESIDENTIAL", "residential"),
                            ("COMMERCIAL", "commercial"),
                            ("INDUSTRIAL", "industrial"),
                            ("AGRICULTURAL", "agricultural"),
                            ("OTHER", "other"),
                        ],
                        default="RESIDENTIAL",
                        max_length=255,
                        null=True,
                    ),
                ),
                ("number_of_floors", models.IntegerField(blank=True, null=True)),
                ("built_area_in_sqft", models.FloatField(blank=True, null=True)),
                ("area_in_sqft", models.FloatField(blank=True, null=True)),
                ("latitude", models.FloatField(blank=True, null=True)),
                ("longitude", models.FloatField(blank=True, null=True)),
                (
                    "return_type",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("RENT", "rent"),
                            ("APPRECIATION", "appreciation"),
                            ("OTHER", "other"),
                        ],
                        default="RENT",
                        max_length=255,
                        null=True,
                    ),
                ),
                ("number_of_rooms", models.IntegerField(blank=True, null=True)),
                ("valuation", models.FloatField(blank=True, null=True)),
                ("has_loan", models.BooleanField(default=False)),
                ("is_verified", models.BooleanField(default=False)),
                ("is_approved", models.BooleanField(default=False)),
                ("is_active", models.BooleanField(default=True)),
                ("other_details", models.JSONField(blank=True, null=True)),
            ],
            options={
                "get_latest_by": "updated_at",
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="PropertyDataAndDocument",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, db_index=True, null=True),
                ),
                ("updated_at", models.DateTimeField(auto_now=True, null=True)),
                ("meta", models.JSONField(blank=True, null=True)),
                (
                    "uuid",
                    models.UUIDField(db_index=True, default=uuid.uuid4, unique=True),
                ),
                ("is_deleted", models.BooleanField(db_index=True, default=False)),
                (
                    "document_type",
                    models.CharField(
                        choices=[
                            ("PROPERTY_PAPER", "property_paper"),
                            ("PROPERTY_IMAGE", "property_image"),
                            ("PROPERTY_VIDEO", "property_video"),
                            ("LOAN_DOCUMENT", "loan_document"),
                            ("RENTAL_DOCUMENT", "rental_document"),
                            ("OTHER_DOCUMENT", "other_document"),
                        ],
                        max_length=255,
                        null=True,
                    ),
                ),
                ("document_date", models.DateField(null=True)),
                ("document_expiry_date", models.DateField(null=True)),
                ("document", models.URLField(null=True)),
                (
                    "property",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="property_documents",
                        to="property.property",
                    ),
                ),
            ],
            options={
                "get_latest_by": "updated_at",
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="PropertyValuationHistory",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, db_index=True, null=True),
                ),
                ("updated_at", models.DateTimeField(auto_now=True, null=True)),
                ("meta", models.JSONField(blank=True, null=True)),
                (
                    "uuid",
                    models.UUIDField(db_index=True, default=uuid.uuid4, unique=True),
                ),
                ("is_deleted", models.BooleanField(db_index=True, default=False)),
                ("valuation", models.FloatField(null=True)),
                ("is_active", models.BooleanField(default=True)),
                (
                    "property",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        to="property.property",
                    ),
                ),
            ],
            options={
                "get_latest_by": "updated_at",
                "abstract": False,
            },
        ),
    ]
