# Generated by Django 5.1.3 on 2025-01-22 07:48

import django.core.validators
import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("property", "0001_initial"),
        ("user", "0002_alter_user_options_alter_user_unique_together_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="property",
            name="investment_lock_in_period_in_months",
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name="property",
            name="sold_percentage",
            field=models.FloatField(
                blank=True,
                default=0.0,
                null=True,
                validators=[
                    django.core.validators.MinValueValidator(0.0),
                    django.core.validators.MaxValueValidator(100.0),
                ],
            ),
        ),
        migrations.AlterField(
            model_name="propertyvaluationhistory",
            name="property",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="valuation_history",
                to="property.property",
            ),
        ),
        migrations.CreateModel(
            name="PropertyRentalData",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, db_index=True, null=True),
                ),
                ("updated_at", models.DateTimeField(auto_now=True, null=True)),
                ("meta", models.JSONField(blank=True, null=True)),
                (
                    "uuid",
                    models.UUIDField(db_index=True, default=uuid.uuid4, unique=True),
                ),
                ("is_deleted", models.BooleanField(db_index=True, default=False)),
                (
                    "rental_area_type",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("ROOM", "room"),
                            ("FLAT", "flat"),
                            ("HOUSE", "house"),
                            ("OTHER", "other"),
                            ("COMMERCIAL", "commercial"),
                        ],
                        default="ROOM",
                        max_length=255,
                        null=True,
                    ),
                ),
                (
                    "house_number",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                ("floor_number", models.IntegerField(blank=True, null=True)),
                ("room_number", models.IntegerField(blank=True, null=True)),
                ("rent_per_month", models.FloatField(blank=True, null=True)),
                ("due_date", models.IntegerField(blank=True, null=True)),
                ("security_deposit", models.FloatField(blank=True, null=True)),
                (
                    "agreement",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        to="property.propertyrelateddataanddocument",
                    ),
                ),
                (
                    "property",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="rental_data",
                        to="property.property",
                    ),
                ),
            ],
            options={
                "get_latest_by": "updated_at",
                "abstract": False,
            },
        ),
        migrations.RenameModel(
            old_name="PropertyDataAndDocument",
            new_name="PropertyRelatedDataAndDocument",
        ),
        migrations.CreateModel(
            name="Survey",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, db_index=True, null=True),
                ),
                ("updated_at", models.DateTimeField(auto_now=True, null=True)),
                ("meta", models.JSONField(blank=True, null=True)),
                (
                    "uuid",
                    models.UUIDField(db_index=True, default=uuid.uuid4, unique=True),
                ),
                ("is_deleted", models.BooleanField(db_index=True, default=False)),
                ("surveyor_id", models.UUIDField()),
                (
                    "surveyor_name",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                (
                    "surveyor_number",
                    models.CharField(blank=True, max_length=10, null=True),
                ),
                (
                    "surveyor_alt_number",
                    models.CharField(blank=True, max_length=10, null=True),
                ),
                (
                    "surveyor_email",
                    models.EmailField(blank=True, max_length=100, null=True),
                ),
                ("description", models.TextField(blank=True, null=True)),
                (
                    "property",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="surveys",
                        to="property.property",
                    ),
                ),
                (
                    "surveyed_valuation",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        to="property.propertyvaluationhistory",
                    ),
                ),
                (
                    "surveyor_govt_id_proof",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        to="property.propertyrelateddataanddocument",
                    ),
                ),
            ],
            options={
                "get_latest_by": "updated_at",
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="UserProperty",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, db_index=True, null=True),
                ),
                ("updated_at", models.DateTimeField(auto_now=True, null=True)),
                ("meta", models.JSONField(blank=True, null=True)),
                (
                    "uuid",
                    models.UUIDField(db_index=True, default=uuid.uuid4, unique=True),
                ),
                ("is_deleted", models.BooleanField(db_index=True, default=False)),
                (
                    "property",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="user_properties",
                        to="property.property",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="user_properties",
                        to="user.user",
                    ),
                ),
            ],
            options={
                "get_latest_by": "updated_at",
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="UserPropertyAmount",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, db_index=True, null=True),
                ),
                ("updated_at", models.DateTimeField(auto_now=True, null=True)),
                ("meta", models.JSONField(blank=True, null=True)),
                (
                    "uuid",
                    models.UUIDField(db_index=True, default=uuid.uuid4, unique=True),
                ),
                ("is_deleted", models.BooleanField(db_index=True, default=False)),
                ("total_amount", models.FloatField(null=True)),
                ("total_investment", models.FloatField(null=True)),
                ("total_withdrawal", models.FloatField(null=True)),
                ("total_profit", models.FloatField(null=True)),
                ("total_loss", models.FloatField(null=True)),
                (
                    "property",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="user_property_amounts",
                        to="property.property",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        to="user.user",
                    ),
                ),
            ],
            options={
                "get_latest_by": "updated_at",
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="UserPropertyStake",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, db_index=True, null=True),
                ),
                ("updated_at", models.DateTimeField(auto_now=True, null=True)),
                ("meta", models.JSONField(blank=True, null=True)),
                (
                    "uuid",
                    models.UUIDField(db_index=True, default=uuid.uuid4, unique=True),
                ),
                ("is_deleted", models.BooleanField(db_index=True, default=False)),
                ("stake_in_percent", models.FloatField(null=True)),
                (
                    "property",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="property_stakes",
                        to="property.property",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="stake",
                        to="user.user",
                    ),
                ),
            ],
            options={
                "get_latest_by": "updated_at",
                "abstract": False,
            },
        ),
    ]
