# Generated by Django 5.1.3 on 2025-01-24 11:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("property", "0002_property_investment_lock_in_period_in_months_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="property",
            name="city",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="property",
            name="country",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="property",
            name="pin_code",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="property",
            name="state",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
