# Generated by Django 5.1.3 on 2025-01-24 12:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("property", "0003_property_city_property_country_property_pin_code_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="property",
            options={},
        ),
        migrations.AddField(
            model_name="property",
            name="govt_allotted_property_id",
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterUniqueTogether(
            name="property",
            unique_together={
                ("name", "address", "city", "state", "country", "pin_code")
            },
        ),
    ]
