# Generated by Django 5.1.3 on 2025-01-24 17:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("property", "0004_alter_property_options_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="property",
            name="govt_allotted_property_id",
            field=models.CharField(max_length=255, null=True, unique=True),
        ),
    ]
