# Generated by Django 5.1.3 on 2025-02-07 16:14

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("property", "0005_alter_property_govt_allotted_property_id"),
        ("user", "0002_alter_user_options_alter_user_unique_together_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="PropertyApprovalRequest",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, db_index=True, null=True),
                ),
                ("updated_at", models.DateTimeField(auto_now=True, null=True)),
                ("meta", models.JSONField(blank=True, null=True)),
                (
                    "uuid",
                    models.UUIDField(db_index=True, default=uuid.uuid4, unique=True),
                ),
                ("is_deleted", models.BooleanField(db_index=True, default=False)),
                ("is_approved", models.BooleanField(default=False)),
                ("is_rejected", models.BooleanField(default=False)),
                ("reason", models.TextField(null=True)),
                ("approved_rejected_on", models.DateTimeField(null=True)),
                (
                    "approved_rejected_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="approval_requests_approved_rejected",
                        to="user.user",
                    ),
                ),
                (
                    "property",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="approval_requests",
                        to="property.property",
                    ),
                ),
                (
                    "requested_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="approval_requests_requested",
                        to="user.user",
                    ),
                ),
            ],
            options={
                "get_latest_by": "updated_at",
                "abstract": False,
            },
        ),
    ]
