# Generated by Django 5.1.3 on 2025-02-08 12:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("property", "0006_propertyapprovalrequest"),
    ]

    operations = [
        migrations.AddField(
            model_name="property",
            name="amenities",
            field=models.JSONField(blank=True, null=True),
        ),
    ]
