# Generated by Django 5.1.3 on 2025-02-26 16:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("property", "0007_property_amenities"),
    ]

    operations = [
        migrations.AlterField(
            model_name="property",
            name="return_type",
            field=models.CharField(
                blank=True,
                choices=[
                    ("RENT", "rent"),
                    ("APPRECIATION", "appriciation"),
                    ("OTHER", "other"),
                ],
                default="RENT",
                max_length=255,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="propertyrelateddataanddocument",
            name="document_type",
            field=models.CharField(
                choices=[
                    ("PROPERTY_PAPER", "property_paper"),
                    ("PROPERTY_IMAGE", "property_image"),
                    ("PROPERTY_VIDEO", "property_video"),
                    ("LOAN_DOCUMENT", "loan_document"),
                    ("PROPERTY_DOCUMENT", "property_document"),
                    ("OTHER_DOCUMENT", "other_document"),
                ],
                max_length=255,
                null=True,
            ),
        ),
    ]
